os:
    - linux
    - osx
matrix:
    allow_failures:
        - os: osx
before_install:
    - ./travis-get-deps.sh
language: cpp
compiler:
    - gcc
    - clang
script: make
after_script:
    - "make test && cd test && ./test"
