before_install:
    - sudo apt-get update
    - sudo apt-get install -qq libsqlite3-dev libcurl4-openssl-dev libxml2-dev libstfl-dev libjson-c-dev libncursesw5-dev bc
language: cpp
compiler:
    - gcc
    - clang
script: make
after_script:
    - "make test && cd test && ./test"
