os:
    - linux
    - osx

install:
    - cd ${TRAVIS_BUILD_DIR}
    - ./travis-get-deps.sh
language: cpp
compiler:
    - gcc
    - clang

script:
    - cd ${TRAVIS_BUILD_DIR}
    - make all test test-rss
    - cd test && ./test-rss && ./test

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - make distclean
    - make PROFILE=1 all test test-rss
    - cd test && ./test-rss && ./test
