before_install:
    - sudo apt-get install libsqlite3-dev libcurl4-openssl-dev libxml2-dev libstfl-dev libjson0-dev libncursesw5-dev bc
language: cpp
compiler:
    - gcc
script: make
after_script:
    - "make test && cd test && ./test"
