before_install:
    - sudo apt-add-repository -y ppa:ondrej/php5-experimental
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install -qq libsqlite3-dev libcurl4-openssl-dev libxml2-dev libstfl-dev libjson-c-dev libncursesw5-dev bc gcc-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
language: cpp
compiler:
    - gcc
    - clang
script: make
after_script:
    - "make test && cd test && ./test"
