language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
    - compiler: gcc
      os: osx
      env: COMPILER=g++
    - compiler: clang
      os: osx
      env: COMPILER=clang++

install:
    - export CXX=$COMPILER
    - cd ${TRAVIS_BUILD_DIR}
    - ./travis-get-deps.sh

script:
    - cd ${TRAVIS_BUILD_DIR}
    - make all test test-rss
    - cd test && ./test-rss && ./test

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - make distclean
    - make PROFILE=1 all test test-rss
    - cd test && ./test-rss && ./test
